In [3]:
import sys
import numpy
import pandas

import sklearn

print("Python :{}".format(sys.version))
print("Numpy  :{}".format(numpy.__version__))
print("Pandas  :{}".format(pandas.__version__))
print("Sklearn  :{}".format(sklearn.__version__))

print("WE are GOOD!")

Python :3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Numpy  :1.18.1
Pandas  :0.25.3
Sklearn  :0.22.1
WE are GOOD!


In [5]:
import pandas as pd
# reading Training dataset

df = pd.read_csv('train_csv.csv')
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [13]:
# CheChecking  data type of X data
X.dtypes


Clump_Thickness                 int64
Uniformity_of_Cell_size         int64
Uniformity_of_Cell_Shape        int64
Marginal_Adhesion               int64
Single_Eplithelial_Cell_Size    int64
Bare_Nuclei                     int64
Bland_Chromatin                 int64
Normal_Nucleoli                 int64
Mitoses                         int64
dtype: object

In [14]:
# cheeking datatype of Y
Y.dtypes

dtype('int64')

In [16]:
# importing our knn Model

from sklearn.neighbors import KNeighborsClassifier
# defing knn model with 5 beighbour
knn = KNeighborsClassifier(n_neighbors=5)


In [19]:
import numpy as np
from sklearn.model_selection import cross_val_score
# performing Cross_validation to avoid Overfitting

score1 = cross_val_score(knn,X,Y,cv=10)
print("Score : ",score1)
print("Average : ",np.average(score1))

Score :  [0.94339623 0.98113208 0.94339623 1.         0.96153846 0.94230769
 0.98076923 0.98076923 0.96153846 0.96153846]
Average :  0.9656386066763425


In [23]:
knn_model = knn.fit(X,Y)
knn_model.score(X,Y)

0.9770992366412213

In [24]:
knn2 = KNeighborsClassifier(n_neighbors=5)
knn2.fit(X,Y)
knn2.score(X,Y)

0.9770992366412213

In [31]:
# performing test on test dataset .
df = pd.read_csv('test_csv.csv')
X_test = df.iloc[:,:-1]
y_test = df.iloc[:,-1]



In [32]:
y_pred=knn_model.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(y_test,y_pred)

0.9771428571428571

In [35]:
confusion_matrix(y_test,y_pred)

array([[117,   3],
       [  1,  54]], dtype=int64)

In [36]:
# saving our model 
import joblib
# saving trained model in current directory
joblib.dump(knn_model,'knn_train_model.joblib')

['knn_train_model.joblib']

In [37]:
# loading our model
knn_load = joblib.load('knn_train_model.joblib')

In [38]:
# prediction with loaded model
y_prediction = knn_load.predict(X_test)

In [39]:
# cheeking the accuracy of loaded model
accuracy_score(y_test,y_prediction)

0.9771428571428571

In [40]:
confusion_matrix(y_test,y_prediction)

array([[117,   3],
       [  1,  54]], dtype=int64)

In [45]:
# testing our prediction using sample 
example = np.array([[4,2,1,1,1,2,3,2,10]])
example = example.reshape(len(example),-1)
prediction = knn_load.predict(example)
print(prediction)
print(type(prediction))
if prediction == 2:
    print("yes")
if prediction == 4:
    print("No")

[2]
<class 'numpy.ndarray'>
yes


In [43]:
a ="12"
print(type(a))
aa = int(a)
print(type(aa))


<class 'str'>
<class 'int'>


In [47]:
# joblib save model is not working with visual studio 
# try an pickle method to save the model.
import pickle

# save the model to disk
filename = 'knn_Trained_Pickle.sav'
pickle.dump(knn_model, open(filename, 'wb'))
 


In [48]:
 
# load the model from disk

filename = 'knn_Trained_Pickle.sav'
loaded_model = pickle.load(open(filename, 'rb'))

In [49]:
y_p = loaded_model.predict(X_test)
confusion_matrix(y_test,y_p)

array([[117,   3],
       [  1,  54]], dtype=int64)